services:
  - type: web
    name: QubticTechnologies
    env: python
    rootDir: census_app
    buildCommand: pip install -r ../requirements.txt
    startCommand: streamlit run census.py --server.port $PORT --server.address 0.0.0.0

